### ISSUE TITLE
define IDE

### ISSUE THREAD

**Issue by 9Lukas5** [HFT-WS16-IF-Rookies/IPR-WS1718-Einkaufsplaner#5]
I guess you all used Atom for the last tasks, I used Netbeans.

I'd just like to avoid to install another IDE, aswell as to atleast use someting available for Linux.
What do you think about that?

**Comment by ewolf34** [comment]
I don´t realy like netbeans in Web Programming

**Comment by kevinkammleiter** [comment]
Well, I don't prefer NetBeans at all, 9Lukas5 should know that. I would suggest a [poll](http://www.strawpoll.me/14495987) to settle on an IDE we're going to use. But as always we should keep an open mind.

**Comment by 9Lukas5** [comment]
I've checked and saw Atom is available as native Linux Appliation, too.
So, I'd go with you to use Atom.

If the poll @kevinkammleiter  linked to, is complete, I'll close this issue.

**Comment by 9Lukas5** [comment]
The IDE will be Atom, as clearly seen in the poll.

I've written the settings that have/should be applied to the IDE while working on this project into the readme in the root directory [here](../blob/dev/README.md#ide).

The linefeed setting is to make it consistent. As Mac, Linux and git use LF by default and Windows is clearly capable of handling LF lineendings by now, we'll use this as lineend character.
Additionally would git have to convert each time a commit/checkout/pull whatever happens, between CRLF and LF in background, which is unneeded.

Please everyone leave a thumbs-up if agree with the IDE definitions, or a thumbs-down if not and a comment what should be changed and why.
